{
    "AdditionalCost": "0",
    "AddlDiscAmt": "0",
    "AddlDiscPercent": "0",
    "Address1": "",
    "Address2": "",
    "Address3": "",
    "AllowCashReceiptMoreSaleAmt": true,
    "Balance": 0,
    "BankAmount": 0,
    "BankID": null,
    "BatchID": "1",
    "BillDiscAmt": 0,
    "BillDiscPercent": 0,
    "BranchID": 1,
    "CGSTAmount": 0,
    "CardNumber": null,
    "CardTypeID": "33",
    "CashID": null,
    "CashReceived": 50,
    "CompanyID": "8ae6a8c2-dc63-4d3c-95be-ff283fdcbfb0",
    "Country_of_Supply": "94e4ce66-26cc-4851-af1e-ecc068e80224",
    "CreatedUserID": 2,
    "CreditPeriod": "0",
    "CustomerName": "Walk-In Customer",
    "Date": "2021-12-13",
    "EmployeeID": "2",
    "FinacialYearID": "1",
    "GST_Treatment": 3,
    "GrandTotal": "50.00",
    "IGSTAmount": 0,
    "INOUT": false,
    "InvoiceNo": 34,
    "IsActive": true,
    "IsPosted": true,
    "KFCAmount": "0",
    "LedgerID": 1,
    "LoyaltyCustomerID": "",
    "Loyalty_Point_Expire": false,
    "NetTotal": "50.00",
    "NoOfGuests": null,
    "Notes": "",
    "OldLedgerBalance": "0",
    "PreFix": "SI",
    "PriceCategoryID": null,
    "PriceRounding": "2",
    "RadeemPoint": "",
    "RoundOff": "0",
    "SAC": "",
    "SGSTAmount": 0,
    "SalesAccount": "85",
    "SalesDetails": [
        {
           "AddlDiscAmt": 0,
           "AddlDiscPerc": 0,
           "BatchCode": 0,
           "CGSTAmount": 0,
           "CGSTPerc": 0,
           "CostPerPrice": "9.45000000",
           "Description": "قلم باسكة",
           "DiscountAmount": "0",
           "DiscountPerc": "0",
           "Flavour": "",
           "FreeQty": 0,
           "GrossAmount": 25,
           "IGSTAmount": 0,
           "IGSTPerc": 0,
           "InclusivePrice": 25,
           "KFCAmount": 0,
           "KFCPerc": 0,
           "NetAmount": 25,
           "PriceListID": 316,
           "ProductID": 114,
           "ProductTaxID": 2,
           "Qty": "1",
           "RateWithTax": 25,
           "SGSTAmount": 0,
           "SGSTPerc": 0,
           "SerialNos": [

           ],
            "TAX1Amount":0,
            "TAX1Perc":0,
            "TAX2Amount":0,
            "TAX2Perc":0,
            "TAX3Amount":0,
            "TAX3Perc":0,
            "TaxableAmount":25,
            "UnitPrice":"25.00",
            "VATAmount":0,
            "VATPerc":0,
            "is_inclusive":false
        }
    ],
    "SalesTax": "0",
    "SalesType": "",
    "SalesTypeOrderNo": null,
    "SeatNumber": null,
    "Seperator": "",
    "ShippingAddress": null,
    "ShippingCharge": "0",
    "State_of_Supply": "12f2f7fa-e007-4170-905a-30b534ab3363",
    "TAX1Amount": "0",
    "TAX2Amount": "0",
    "TAX3Amount": "0",
    "TableID": null,
    "TaxID": 32,
    "TaxType": "VAT",
    "TaxTypeID": null,
    "TaxableAmount": 0,
    "TokenNumber": null,
    "TotalDiscount": 0,
    "TotalGrossAmt": "50.00",
    "TotalTax": 0,
    "TransactionTypeID": "1",
    "VATAmount": 0,
    "VAT_Treatment": 1,
    "VoucherNo": "SI34",
    "WarehouseID": "1",
    "order_vouchers": [

    ],
    "shipping_tax_amount": "0"
}
