from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve

from api.v1.users import views as users_views
from users import views as general_views

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^api-auth/", include("rest_framework.urls")),
    path(
        "api/v1/auth/",
        include(
            ("api.v1.authentication.urls", "api"), namespace="api_v1_authentication"
        ),
    ),
    url(r"^app/accounts/", include("registration.backends.default.urls")),
    url("", include("pwa.urls")),
    path("api/v1/users/", include("api.v1.users.urls")),
    path("api/v1/brands/", include("api.v1.brands.urls")),
    path("api/v1/units/", include("api.v1.units.urls")),
    path("api/v1/routes/", include("api.v1.routes.urls")),
    path("api/v1/taxCategories/", include("api.v1.taxCategories.urls")),
    path("api/v1/productCategories/", include("api.v1.productCategories.urls")),
    path("api/v1/productGroups/", include("api.v1.productGroups.urls")),
    path("api/v1/warehouses/", include("api.v1.warehouses.urls")),
    path("api/v1/priceCategories/", include("api.v1.priceCategories.urls")),
    path("api/v1/accountGroups/", include("api.v1.accountGroups.urls")),
    path("api/v1/accountLedgers/", include("api.v1.accountLedgers.urls")),
    path("api/v1/branchs/", include("api.v1.branchs.urls")),
    path("api/v1/parties/", include("api.v1.parties.urls")),
    path("api/v1/products/", include("api.v1.products.urls")),
    path("api/v1/priceLists/", include("api.v1.priceLists.urls")),
    path("api/v1/masterTypes/", include("api.v1.masterTypes.urls")),
    path("api/v1/transactionTypes/", include("api.v1.transactionTypes.urls")),
    path("api/v1/colors/", include("api.v1.colors.urls")),
    path("api/v1/companySettings/", include("api.v1.companySettings.urls")),
    path("api/v1/damageStockDetails/", include("api.v1.damageStockDetails.urls")),
    path("api/v1/damageStockMaster/", include("api.v1.damageStockMaster.urls")),
    path("api/v1/designation/", include("api.v1.designation.urls")),
    path("api/v1/department/", include("api.v1.department.urls")),
    path("api/v1/employees/", include("api.v1.employees.urls")),
    path("api/v1/flavours/", include("api.v1.flavours.urls")),
    path("api/v1/journalDetails/", include("api.v1.journalDetails.urls")),
    path("api/v1/journalMaster/", include("api.v1.journalMaster.urls")),
    path("api/v1/kitchen/", include("api.v1.kitchen.urls")),
    path("api/v1/ledgerPosting/", include("api.v1.ledgerPosting.urls")),
    path("api/v1/openingStockDetails/", include("api.v1.openingStockDetails.urls")),
    path("api/v1/openingStockMaster/", include("api.v1.openingStockMaster.urls")),
    path("api/v1/paymentDetails/", include("api.v1.paymentDetails.urls")),
    path("api/v1/paymentMaster/", include("api.v1.paymentMaster.urls")),
    path("api/v1/POSHoldDetails/", include("api.v1.POSHoldDetails.urls")),
    path("api/v1/POSHoldMaster/", include("api.v1.POSHoldMaster.urls")),
    path("api/v1/purchaseDetails/", include("api.v1.purchaseDetails.urls")),
    path("api/v1/purchaseMaster/", include("api.v1.purchaseMaster.urls")),
    path("api/v1/purchaseOrderDetails/", include("api.v1.purchaseOrderDetails.urls")),
    path("api/v1/purchaseOrderMaster/", include("api.v1.purchaseOrderMaster.urls")),
    path("api/v1/purchaseReturnDetails/", include("api.v1.purchaseReturnDetails.urls")),
    path("api/v1/purchaseReturnMaster/", include("api.v1.purchaseReturnMaster.urls")),
    path("api/v1/receiptDetails/", include("api.v1.receiptDetails.urls")),
    path("api/v1/receiptMaster/", include("api.v1.receiptMaster.urls")),
    path("api/v1/salesDetails/", include("api.v1.salesDetails.urls")),
    path("api/v1/salesMaster/", include("api.v1.salesMaster.urls")),
    path("api/v1/salesOrderDetails/", include("api.v1.salesOrderDetails.urls")),
    path("api/v1/salesOrderMaster/", include("api.v1.salesOrderMaster.urls")),
    path("api/v1/salesReturnDetails/", include("api.v1.salesReturnDetails.urls")),
    path("api/v1/salesReturnMaster/", include("api.v1.salesReturnMaster.urls")),
    path("api/v1/settings/", include("api.v1.settings.urls")),
    path(
        "api/v1/stockAdjustmentDetails/", include("api.v1.stockAdjustmentDetails.urls")
    ),
    path("api/v1/stockAdjustmentMaster/", include("api.v1.stockAdjustmentMaster.urls")),
    path("api/v1/stockReceiptDetails/", include("api.v1.stockReceiptDetails.urls")),
    path("api/v1/stockReceiptMasterID/", include("api.v1.stockReceiptMasterID.urls")),
    path("api/v1/stockTransferDetails/", include("api.v1.stockTransferDetails.urls")),
    path("api/v1/stockTransferMasterID/", include("api.v1.stockTransferMasterID.urls")),
    path("api/v1/stockPostings/", include("api.v1.stockPostings.urls")),
    path("api/v1/stockRates/", include("api.v1.stockRates.urls")),
    path("api/v1/banks/", include("api.v1.banks.urls")),
    path("api/v1/financialYear/", include("api.v1.financialYear.urls")),
    path("api/v1/damageStock/", include("api.v1.damageStock.urls")),
    path("api/v1/openingStock/", include("api.v1.openingStock.urls")),
    path("api/v1/payments/", include("api.v1.payments.urls")),
    path("api/v1/posholds/", include("api.v1.posholds.urls")),
    path("api/v1/purchases/", include("api.v1.purchases.urls")),
    path("api/v1/receipts/", include("api.v1.receipts.urls")),
    path("api/v1/purchaseOrders/", include("api.v1.purchaseOrders.urls")),
    path("api/v1/purchaseReturns/", include("api.v1.purchaseReturns.urls")),
    path("api/v1/sales/", include("api.v1.sales.urls")),
    path("api/v1/salesOrders/", include("api.v1.salesOrders.urls")),
    path("api/v1/salesReturns/", include("api.v1.salesReturns.urls")),
    path("api/v1/stockAdjustments/", include("api.v1.stockAdjustments.urls")),
    path("api/v1/stockReceipts/", include("api.v1.stockReceipts.urls")),
    path("api/v1/stockTransfers/", include("api.v1.stockTransfers.urls")),
    path("api/v1/journals/", include("api.v1.journals.urls")),
    path("api/v1/countries/", include("api.v1.countries.urls")),
    path("api/v1/states/", include("api.v1.states.urls")),
    path("api/v1/businessTypes/", include("api.v1.businessTypes.urls")),
    path("api/v1/organizations/", include("api.v1.organizations.urls")),
    path("api/v1/userTable/", include("api.v1.userTable.urls")),
    path(
        "api/v1/reset-password/",
        include("django_rest_passwordreset.urls", namespace="password_reset"),
    ),
    # version2 urls
    path("api/v2/users/", include("api.v2.users.urls")),
    path("api/v2/brands/", include("api.v2.brands.urls")),
    path("api/v2/units/", include("api.v2.units.urls")),
    path("api/v2/routes/", include("api.v2.routes.urls")),
    path("api/v2/taxCategories/", include("api.v2.taxCategories.urls")),
    path("api/v2/productCategories/", include("api.v2.productCategories.urls")),
    path("api/v2/productGroups/", include("api.v2.productGroups.urls")),
    path("api/v2/warehouses/", include("api.v2.warehouses.urls")),
    path("api/v2/priceCategories/", include("api.v2.priceCategories.urls")),
    path("api/v2/accountGroups/", include("api.v2.accountGroups.urls")),
    path("api/v2/accountLedgers/", include("api.v2.accountLedgers.urls")),
    path("api/v2/branchs/", include("api.v2.branchs.urls")),
    path("api/v2/parties/", include("api.v2.parties.urls")),
    path("api/v2/products/", include("api.v2.products.urls")),
    path("api/v2/priceLists/", include("api.v2.priceLists.urls")),
    path("api/v2/masterTypes/", include("api.v2.masterTypes.urls")),
    path("api/v2/transactionTypes/", include("api.v2.transactionTypes.urls")),
    path("api/v2/colors/", include("api.v2.colors.urls")),
    path("api/v2/companySettings/", include("api.v2.companySettings.urls")),
    path("api/v2/damageStockDetails/", include("api.v2.damageStockDetails.urls")),
    path("api/v2/damageStockMaster/", include("api.v2.damageStockMaster.urls")),
    path("api/v2/designation/", include("api.v2.designation.urls")),
    path("api/v2/department/", include("api.v2.department.urls")),
    path("api/v2/employees/", include("api.v2.employees.urls")),
    path("api/v2/flavours/", include("api.v2.flavours.urls")),
    path("api/v2/journalDetails/", include("api.v2.journalDetails.urls")),
    path("api/v2/journalMaster/", include("api.v2.journalMaster.urls")),
    path("api/v2/kitchen/", include("api.v2.kitchen.urls")),
    path("api/v2/ledgerPosting/", include("api.v2.ledgerPosting.urls")),
    path("api/v2/openingStockDetails/", include("api.v2.openingStockDetails.urls")),
    path("api/v2/openingStockMaster/", include("api.v2.openingStockMaster.urls")),
    path("api/v2/paymentDetails/", include("api.v2.paymentDetails.urls")),
    path("api/v2/paymentMaster/", include("api.v2.paymentMaster.urls")),
    path("api/v2/POSHoldDetails/", include("api.v2.POSHoldDetails.urls")),
    path("api/v2/POSHoldMaster/", include("api.v2.POSHoldMaster.urls")),
    path("api/v2/purchaseDetails/", include("api.v2.purchaseDetails.urls")),
    path("api/v2/purchaseMaster/", include("api.v2.purchaseMaster.urls")),
    path("api/v2/purchaseOrderDetails/", include("api.v2.purchaseOrderDetails.urls")),
    path("api/v2/purchaseOrderMaster/", include("api.v2.purchaseOrderMaster.urls")),
    path("api/v2/purchaseReturnDetails/", include("api.v2.purchaseReturnDetails.urls")),
    path("api/v2/purchaseReturnMaster/", include("api.v2.purchaseReturnMaster.urls")),
    path("api/v2/receiptDetails/", include("api.v2.receiptDetails.urls")),
    path("api/v2/receiptMaster/", include("api.v2.receiptMaster.urls")),
    path("api/v2/salesDetails/", include("api.v2.salesDetails.urls")),
    path("api/v2/salesMaster/", include("api.v2.salesMaster.urls")),
    path("api/v2/salesOrderDetails/", include("api.v2.salesOrderDetails.urls")),
    path("api/v2/salesOrderMaster/", include("api.v2.salesOrderMaster.urls")),
    path("api/v2/salesReturnDetails/", include("api.v2.salesReturnDetails.urls")),
    path("api/v2/salesReturnMaster/", include("api.v2.salesReturnMaster.urls")),
    path("api/v2/settings/", include("api.v2.settings.urls")),
    path(
        "api/v2/stockAdjustmentDetails/", include("api.v2.stockAdjustmentDetails.urls")
    ),
    path("api/v2/stockAdjustmentMaster/", include("api.v2.stockAdjustmentMaster.urls")),
    path("api/v2/stockReceiptDetails/", include("api.v2.stockReceiptDetails.urls")),
    path("api/v2/stockReceiptMasterID/", include("api.v2.stockReceiptMasterID.urls")),
    path("api/v2/stockTransferDetails/", include("api.v2.stockTransferDetails.urls")),
    path("api/v2/stockTransferMasterID/", include("api.v2.stockTransferMasterID.urls")),
    path("api/v2/stockPostings/", include("api.v2.stockPostings.urls")),
    path("api/v2/stockRates/", include("api.v2.stockRates.urls")),
    path("api/v2/banks/", include("api.v2.banks.urls")),
    path("api/v2/financialYear/", include("api.v2.financialYear.urls")),
    path("api/v2/workOrder/", include("api.v2.workOrder.urls")),
    path("api/v2/damageStock/", include("api.v2.damageStock.urls")),
    path("api/v2/openingStock/", include("api.v2.openingStock.urls")),
    path("api/v2/payments/", include("api.v2.payments.urls")),
    path("api/v2/posholds/", include("api.v2.posholds.urls")),
    path("api/v2/purchases/", include("api.v2.purchases.urls")),
    path("api/v2/receipts/", include("api.v2.receipts.urls")),
    path("api/v2/purchaseOrders/", include("api.v2.purchaseOrders.urls")),
    path("api/v2/purchaseReturns/", include("api.v2.purchaseReturns.urls")),
    path("api/v2/sales/", include("api.v2.sales.urls")),
    path("api/v2/salesOrders/", include("api.v2.salesOrders.urls")),
    path("api/v2/salesReturns/", include("api.v2.salesReturns.urls")),
    path("api/v2/stockAdjustments/", include("api.v2.stockAdjustments.urls")),
    path("api/v2/stockReceipts/", include("api.v2.stockReceipts.urls")),
    path("api/v2/stockTransfers/", include("api.v2.stockTransfers.urls")),
    path("api/v2/journals/", include("api.v2.journals.urls")),
    path("api/v2/countries/", include("api.v2.countries.urls")),
    path("api/v2/states/", include("api.v2.states.urls")),
    path("api/v2/businessTypes/", include("api.v2.businessTypes.urls")),
    path("api/v2/organizations/", include("api.v2.organizations.urls")),
    path("api/v2/userTable/", include("api.v2.userTable.urls")),
    path("api/v2/translate/", include("api.v2.translate.urls")),
    path("api/v2/dashboard/", include("api.v2.dashboard.urls")),
    path(
        "api/v2/reset-password/",
        include("django_rest_passwordreset.urls", namespace="password_reset2"),
    ),
    # version3 urls
    path("api/v3/users/", include("api.v3.users.urls")),
    path("api/v3/brands/", include("api.v3.brands.urls")),
    path("api/v3/units/", include("api.v3.units.urls")),
    path("api/v3/routes/", include("api.v3.routes.urls")),
    path("api/v3/taxCategories/", include("api.v3.taxCategories.urls")),
    path("api/v3/productCategories/", include("api.v3.productCategories.urls")),
    path("api/v3/productGroups/", include("api.v3.productGroups.urls")),
    path("api/v3/warehouses/", include("api.v3.warehouses.urls")),
    path("api/v3/priceCategories/", include("api.v3.priceCategories.urls")),
    path("api/v3/accountGroups/", include("api.v3.accountGroups.urls")),
    path("api/v3/accountLedgers/", include("api.v3.accountLedgers.urls")),
    path("api/v3/branchs/", include("api.v3.branchs.urls")),
    path("api/v3/parties/", include("api.v3.parties.urls")),
    path("api/v3/products/", include("api.v3.products.urls")),
    path("api/v3/priceLists/", include("api.v3.priceLists.urls")),
    path("api/v3/masterTypes/", include("api.v3.masterTypes.urls")),
    path("api/v3/transactionTypes/", include("api.v3.transactionTypes.urls")),
    path("api/v3/colors/", include("api.v3.colors.urls")),
    path("api/v3/companySettings/", include("api.v3.companySettings.urls")),
    path("api/v3/damageStockDetails/", include("api.v3.damageStockDetails.urls")),
    path("api/v3/damageStockMaster/", include("api.v3.damageStockMaster.urls")),
    path("api/v3/designation/", include("api.v3.designation.urls")),
    path("api/v3/department/", include("api.v3.department.urls")),
    path("api/v3/employees/", include("api.v3.employees.urls")),
    path("api/v3/flavours/", include("api.v3.flavours.urls")),
    path("api/v3/journalDetails/", include("api.v3.journalDetails.urls")),
    path("api/v3/journalMaster/", include("api.v3.journalMaster.urls")),
    path("api/v3/kitchen/", include("api.v3.kitchen.urls")),
    path("api/v3/ledgerPosting/", include("api.v3.ledgerPosting.urls")),
    path("api/v3/openingStockDetails/", include("api.v3.openingStockDetails.urls")),
    path("api/v3/openingStockMaster/", include("api.v3.openingStockMaster.urls")),
    path("api/v3/paymentDetails/", include("api.v3.paymentDetails.urls")),
    path("api/v3/paymentMaster/", include("api.v3.paymentMaster.urls")),
    path("api/v3/POSHoldDetails/", include("api.v3.POSHoldDetails.urls")),
    path("api/v3/POSHoldMaster/", include("api.v3.POSHoldMaster.urls")),
    path("api/v3/purchaseDetails/", include("api.v3.purchaseDetails.urls")),
    path("api/v3/purchaseMaster/", include("api.v3.purchaseMaster.urls")),
    path("api/v3/purchaseOrderDetails/", include("api.v3.purchaseOrderDetails.urls")),
    path("api/v3/purchaseOrderMaster/", include("api.v3.purchaseOrderMaster.urls")),
    path("api/v3/purchaseReturnDetails/", include("api.v3.purchaseReturnDetails.urls")),
    path("api/v3/purchaseReturnMaster/", include("api.v3.purchaseReturnMaster.urls")),
    path("api/v3/receiptDetails/", include("api.v3.receiptDetails.urls")),
    path("api/v3/receiptMaster/", include("api.v3.receiptMaster.urls")),
    path("api/v3/salesDetails/", include("api.v3.salesDetails.urls")),
    path("api/v3/salesMaster/", include("api.v3.salesMaster.urls")),
    path("api/v3/salesOrderDetails/", include("api.v3.salesOrderDetails.urls")),
    path("api/v3/salesOrderMaster/", include("api.v3.salesOrderMaster.urls")),
    path("api/v3/salesReturnDetails/", include("api.v3.salesReturnDetails.urls")),
    path("api/v3/salesReturnMaster/", include("api.v3.salesReturnMaster.urls")),
    path(
        "api/v3/settings/", include("api.v3.settings.urls", namespace="api_v3_settings")
    ),
    path(
        "api/v3/stockAdjustmentDetails/", include("api.v3.stockAdjustmentDetails.urls")
    ),
    path("api/v3/stockAdjustmentMaster/", include("api.v3.stockAdjustmentMaster.urls")),
    path("api/v3/stockReceiptDetails/", include("api.v3.stockReceiptDetails.urls")),
    path("api/v3/stockReceiptMasterID/", include("api.v3.stockReceiptMasterID.urls")),
    path("api/v3/stockTransferDetails/", include("api.v3.stockTransferDetails.urls")),
    path("api/v3/stockTransferMasterID/", include("api.v3.stockTransferMasterID.urls")),
    path("api/v3/stockPostings/", include("api.v3.stockPostings.urls")),
    path("api/v3/stockRates/", include("api.v3.stockRates.urls")),
    path("api/v3/banks/", include("api.v3.banks.urls")),
    path("api/v3/financialYear/", include("api.v3.financialYear.urls")),
    path("api/v3/workOrder/", include("api.v3.workOrder.urls")),
    path("api/v3/damageStock/", include("api.v3.damageStock.urls")),
    path("api/v3/openingStock/", include("api.v3.openingStock.urls")),
    path("api/v3/payments/", include("api.v3.payments.urls")),
    path("api/v3/posholds/", include("api.v3.posholds.urls")),
    path("api/v3/purchases/", include("api.v3.purchases.urls")),
    path("api/v3/receipts/", include("api.v3.receipts.urls")),
    path("api/v3/purchaseOrders/", include("api.v3.purchaseOrders.urls")),
    path("api/v3/purchaseReturns/", include("api.v3.purchaseReturns.urls")),
    path("api/v3/sales/", include("api.v3.sales.urls")),
    path("api/v3/salesOrders/", include("api.v3.salesOrders.urls")),
    path("api/v3/salesReturns/", include("api.v3.salesReturns.urls")),
    path("api/v3/stockAdjustments/", include("api.v3.stockAdjustments.urls")),
    path("api/v3/stockReceipts/", include("api.v3.stockReceipts.urls")),
    path("api/v3/stockTransfers/", include("api.v3.stockTransfers.urls")),
    path("api/v3/journals/", include("api.v3.journals.urls")),
    path("api/v3/countries/", include("api.v3.countries.urls")),
    path("api/v3/states/", include("api.v3.states.urls")),
    path("api/v3/businessTypes/", include("api.v3.businessTypes.urls")),
    path("api/v3/organizations/", include("api.v3.organizations.urls")),
    path("api/v3/userTable/", include("api.v3.userTable.urls")),
    path("api/v3/translate/", include("api.v3.translate.urls")),
    path("api/v3/dashboard/", include("api.v3.dashboard.urls")),
    path("api/v3/userTypes/", include("api.v3.userTypes.urls")),
    path(
        "api/v3/reset-password/",
        include("django_rest_passwordreset.urls", namespace="password_reset3"),
    ),
    # version4 urls
    path("api/v4/users/", include("api.v4.users.urls")),
    path("api/v4/brands/", include("api.v4.brands.urls")),
    path("api/v4/units/", include("api.v4.units.urls")),
    path("api/v4/routes/", include("api.v4.routes.urls")),
    path("api/v4/taxCategories/", include("api.v4.taxCategories.urls")),
    path("api/v4/productCategories/", include("api.v4.productCategories.urls")),
    path("api/v4/productGroups/", include("api.v4.productGroups.urls")),
    path("api/v4/warehouses/", include("api.v4.warehouses.urls")),
    path("api/v4/priceCategories/", include("api.v4.priceCategories.urls")),
    path("api/v4/accountGroups/", include("api.v4.accountGroups.urls")),
    path("api/v4/accountLedgers/", include("api.v4.accountLedgers.urls")),
    path("api/v4/branchs/", include("api.v4.branchs.urls")),
    path("api/v4/parties/", include("api.v4.parties.urls")),
    path("api/v4/products/", include("api.v4.products.urls")),
    path("api/v4/priceLists/", include("api.v4.priceLists.urls")),
    path("api/v4/masterTypes/", include("api.v4.masterTypes.urls")),
    path("api/v4/transactionTypes/", include("api.v4.transactionTypes.urls")),
    path("api/v4/colors/", include("api.v4.colors.urls")),
    path("api/v4/companySettings/", include("api.v4.companySettings.urls")),
    path("api/v4/damageStockDetails/", include("api.v4.damageStockDetails.urls")),
    path("api/v4/damageStockMaster/", include("api.v4.damageStockMaster.urls")),
    path("api/v4/designation/", include("api.v4.designation.urls")),
    path("api/v4/department/", include("api.v4.department.urls")),
    path("api/v4/employees/", include("api.v4.employees.urls")),
    path("api/v4/flavours/", include("api.v4.flavours.urls")),
    path("api/v4/journalDetails/", include("api.v4.journalDetails.urls")),
    path("api/v4/journalMaster/", include("api.v4.journalMaster.urls")),
    path("api/v4/kitchen/", include("api.v4.kitchen.urls")),
    path("api/v4/ledgerPosting/", include("api.v4.ledgerPosting.urls")),
    path("api/v4/openingStockDetails/", include("api.v4.openingStockDetails.urls")),
    path("api/v4/openingStockMaster/", include("api.v4.openingStockMaster.urls")),
    path("api/v4/paymentDetails/", include("api.v4.paymentDetails.urls")),
    path("api/v4/paymentMaster/", include("api.v4.paymentMaster.urls")),
    path("api/v4/POSHoldDetails/", include("api.v4.POSHoldDetails.urls")),
    path("api/v4/POSHoldMaster/", include("api.v4.POSHoldMaster.urls")),
    path("api/v4/purchaseDetails/", include("api.v4.purchaseDetails.urls")),
    path("api/v4/purchaseMaster/", include("api.v4.purchaseMaster.urls")),
    path("api/v4/purchaseOrderDetails/", include("api.v4.purchaseOrderDetails.urls")),
    path("api/v4/purchaseOrderMaster/", include("api.v4.purchaseOrderMaster.urls")),
    path("api/v4/purchaseReturnDetails/", include("api.v4.purchaseReturnDetails.urls")),
    path("api/v4/purchaseReturnMaster/", include("api.v4.purchaseReturnMaster.urls")),
    path("api/v4/receiptDetails/", include("api.v4.receiptDetails.urls")),
    path("api/v4/receiptMaster/", include("api.v4.receiptMaster.urls")),
    path("api/v4/salesDetails/", include("api.v4.salesDetails.urls")),
    path("api/v4/salesMaster/", include("api.v4.salesMaster.urls")),
    path("api/v4/salesOrderDetails/", include("api.v4.salesOrderDetails.urls")),
    path("api/v4/salesOrderMaster/", include("api.v4.salesOrderMaster.urls")),
    path("api/v4/salesReturnDetails/", include("api.v4.salesReturnDetails.urls")),
    path("api/v4/salesReturnMaster/", include("api.v4.salesReturnMaster.urls")),
    path(
        "api/v4/settings/", include("api.v4.settings.urls", namespace="api_v4_settings")
    ),
    path(
        "api/v4/stockAdjustmentDetails/", include("api.v4.stockAdjustmentDetails.urls")
    ),
    path("api/v4/stockAdjustmentMaster/", include("api.v4.stockAdjustmentMaster.urls")),
    path("api/v4/stockReceiptDetails/", include("api.v4.stockReceiptDetails.urls")),
    path("api/v4/stockReceiptMasterID/", include("api.v4.stockReceiptMasterID.urls")),
    path("api/v4/stockTransferDetails/", include("api.v4.stockTransferDetails.urls")),
    path("api/v4/stockTransferMasterID/", include("api.v4.stockTransferMasterID.urls")),
    path("api/v4/stockPostings/", include("api.v4.stockPostings.urls")),
    path("api/v4/stockRates/", include("api.v4.stockRates.urls")),
    path("api/v4/banks/", include("api.v4.banks.urls")),
    path("api/v4/financialYear/", include("api.v4.financialYear.urls")),
    path("api/v4/workOrder/", include("api.v4.workOrder.urls")),
    path("api/v4/damageStock/", include("api.v4.damageStock.urls")),
    path("api/v4/openingStock/", include("api.v4.openingStock.urls")),
    path("api/v4/payments/", include("api.v4.payments.urls")),
    path("api/v4/posholds/", include("api.v4.posholds.urls")),
    path("api/v4/purchases/", include("api.v4.purchases.urls")),
    path("api/v4/receipts/", include("api.v4.receipts.urls")),
    path("api/v4/purchaseOrders/", include("api.v4.purchaseOrders.urls")),
    path("api/v4/purchaseReturns/", include("api.v4.purchaseReturns.urls")),
    path("api/v4/sales/", include("api.v4.sales.urls")),
    path("api/v4/salesOrders/", include("api.v4.salesOrders.urls")),
    path("api/v4/salesEstimates/", include("api.v4.salesEstimates.urls")),
    path("api/v4/salesReturns/", include("api.v4.salesReturns.urls")),
    path("api/v4/stockAdjustments/", include("api.v4.stockAdjustments.urls")),
    path("api/v4/stockReceipts/", include("api.v4.stockReceipts.urls")),
    path("api/v4/stockTransfers/", include("api.v4.stockTransfers.urls")),
    path("api/v4/journals/", include("api.v4.journals.urls")),
    path("api/v4/countries/", include("api.v4.countries.urls")),
    path("api/v4/states/", include("api.v4.states.urls")),
    path("api/v4/businessTypes/", include("api.v4.businessTypes.urls")),
    path("api/v4/organizations/", include("api.v4.organizations.urls")),
    path("api/v4/userTable/", include("api.v4.userTable.urls")),
    path("api/v4/translate/", include("api.v4.translate.urls")),
    path("api/v4/dashboard/", include("api.v4.dashboard.urls")),
    path("api/v4/userTypes/", include("api.v4.userTypes.urls")),
    path("api/v4/category/", include("api.v4.category.urls")),
    path("api/v4/workingTime/", include("api.v4.workingTime.urls")),
    path("api/v4/holiday/", include("api.v4.holiday.urls")),
    path("api/v4/salaryComponent/", include("api.v4.salaryComponent.urls")),
    path("api/v4/salaryKit/", include("api.v4.salaryKit.urls")),
    path("api/v4/salaryPeriod/", include("api.v4.salaryPeriod.urls")),
    path("api/v4/leave/", include("api.v4.leave.urls")),
    path("api/v4/leaveType/", include("api.v4.leaveType.urls")),
    path("api/v4/attendance/", include("api.v4.attendance.urls")),
    path("api/v4/advanceRequest/", include("api.v4.advanceRequest.urls")),
    path("api/v4/loanRequest/", include("api.v4.loanRequest.urls")),
    path("api/v4/loanType/", include("api.v4.loanType.urls")),
    path("api/v4/relieveRequest/", include("api.v4.relieveRequest.urls")),
    path("api/v4/leaveRequest/", include("api.v4.leaveRequest.urls")),
    path("api/v4/loyaltyCustomer/", include("api.v4.loyaltyCustomer.urls")),
    path("api/v4/loyaltyProgram/", include("api.v4.loyaltyProgram.urls")),
    path(
        "api/v4/reset-password/",
        include("django_rest_passwordreset.urls", namespace="password_reset4"),
    ),
    # version5 urls
    path("api/v5/users/", include("api.v5.users.urls")),
    path("api/v5/brands/", include("api.v5.brands.urls")),
    path("api/v5/units/", include("api.v5.units.urls")),
    path("api/v5/routes/", include("api.v5.routes.urls")),
    path("api/v5/taxCategories/", include("api.v5.taxCategories.urls")),
    path("api/v5/productCategories/", include("api.v5.productCategories.urls")),
    path("api/v5/productGroups/", include("api.v5.productGroups.urls")),
    path("api/v5/warehouses/", include("api.v5.warehouses.urls")),
    path("api/v5/priceCategories/", include("api.v5.priceCategories.urls")),
    path("api/v5/accountGroups/", include("api.v5.accountGroups.urls")),
    path("api/v5/accountLedgers/", include("api.v5.accountLedgers.urls")),
    path("api/v5/branchs/", include("api.v5.branchs.urls")),
    path("api/v5/parties/", include("api.v5.parties.urls")),
    path("api/v5/products/", include("api.v5.products.urls")),
    path("api/v5/priceLists/", include("api.v5.priceLists.urls")),
    path("api/v5/masterTypes/", include("api.v5.masterTypes.urls")),
    path("api/v5/transactionTypes/", include("api.v5.transactionTypes.urls")),
    path("api/v5/colors/", include("api.v5.colors.urls")),
    path("api/v5/companySettings/", include("api.v5.companySettings.urls")),
    path("api/v5/damageStockDetails/", include("api.v5.damageStockDetails.urls")),
    path("api/v5/damageStockMaster/", include("api.v5.damageStockMaster.urls")),
    path("api/v5/designation/", include("api.v5.designation.urls")),
    path("api/v5/department/", include("api.v5.department.urls")),
    path("api/v5/employees/", include("api.v5.employees.urls")),
    path("api/v5/flavours/", include("api.v5.flavours.urls")),
    path("api/v5/journalDetails/", include("api.v5.journalDetails.urls")),
    path("api/v5/journalMaster/", include("api.v5.journalMaster.urls")),
    path("api/v5/kitchen/", include("api.v5.kitchen.urls")),
    path("api/v5/ledgerPosting/", include("api.v5.ledgerPosting.urls")),
    path("api/v5/openingStockDetails/", include("api.v5.openingStockDetails.urls")),
    path("api/v5/openingStockMaster/", include("api.v5.openingStockMaster.urls")),
    path("api/v5/paymentDetails/", include("api.v5.paymentDetails.urls")),
    path("api/v5/paymentMaster/", include("api.v5.paymentMaster.urls")),
    path("api/v5/POSHoldDetails/", include("api.v5.POSHoldDetails.urls")),
    path("api/v5/POSHoldMaster/", include("api.v5.POSHoldMaster.urls")),
    path("api/v5/purchaseDetails/", include("api.v5.purchaseDetails.urls")),
    path("api/v5/purchaseMaster/", include("api.v5.purchaseMaster.urls")),
    path("api/v5/purchaseOrderDetails/", include("api.v5.purchaseOrderDetails.urls")),
    path("api/v5/purchaseOrderMaster/", include("api.v5.purchaseOrderMaster.urls")),
    path("api/v5/purchaseReturnDetails/", include("api.v5.purchaseReturnDetails.urls")),
    path("api/v5/purchaseReturnMaster/", include("api.v5.purchaseReturnMaster.urls")),
    path("api/v5/receiptDetails/", include("api.v5.receiptDetails.urls")),
    path("api/v5/receiptMaster/", include("api.v5.receiptMaster.urls")),
    path("api/v5/salesDetails/", include("api.v5.salesDetails.urls")),
    path("api/v5/salesMaster/", include("api.v5.salesMaster.urls")),
    path("api/v5/salesOrderDetails/", include("api.v5.salesOrderDetails.urls")),
    path("api/v5/salesOrderMaster/", include("api.v5.salesOrderMaster.urls")),
    path("api/v5/salesReturnDetails/", include("api.v5.salesReturnDetails.urls")),
    path("api/v5/salesReturnMaster/", include("api.v5.salesReturnMaster.urls")),
    path(
        "api/v5/settings/", include("api.v5.settings.urls", namespace="api_v5_settings")
    ),
    path(
        "api/v5/stockAdjustmentDetails/", include("api.v5.stockAdjustmentDetails.urls")
    ),
    path("api/v5/stockAdjustmentMaster/", include("api.v5.stockAdjustmentMaster.urls")),
    path("api/v5/stockReceiptDetails/", include("api.v5.stockReceiptDetails.urls")),
    path("api/v5/stockReceiptMasterID/", include("api.v5.stockReceiptMasterID.urls")),
    path("api/v5/stockTransferDetails/", include("api.v5.stockTransferDetails.urls")),
    path("api/v5/stockTransferMasterID/", include("api.v5.stockTransferMasterID.urls")),
    path("api/v5/stockPostings/", include("api.v5.stockPostings.urls")),
    path("api/v5/stockRates/", include("api.v5.stockRates.urls")),
    path("api/v5/banks/", include("api.v5.banks.urls")),
    path("api/v5/financialYear/", include("api.v5.financialYear.urls")),
    path("api/v5/workOrder/", include("api.v5.workOrder.urls")),
    path("api/v5/damageStock/", include("api.v5.damageStock.urls")),
    path("api/v5/openingStock/", include("api.v5.openingStock.urls")),
    path("api/v5/payments/", include("api.v5.payments.urls")),
    path("api/v5/posholds/", include("api.v5.posholds.urls")),
    path("api/v5/purchases/", include("api.v5.purchases.urls")),
    path("api/v5/receipts/", include("api.v5.receipts.urls")),
    path("api/v5/purchaseOrders/", include("api.v5.purchaseOrders.urls")),
    path("api/v5/purchaseReturns/", include("api.v5.purchaseReturns.urls")),
    path("api/v5/sales/", include("api.v5.sales.urls")),
    path("api/v5/salesOrders/", include("api.v5.salesOrders.urls")),
    path("api/v5/salesEstimates/", include("api.v5.salesEstimates.urls")),
    path("api/v5/salesReturns/", include("api.v5.salesReturns.urls")),
    path("api/v5/stockAdjustments/", include("api.v5.stockAdjustments.urls")),
    path("api/v5/stockReceipts/", include("api.v5.stockReceipts.urls")),
    path("api/v5/stockTransfers/", include("api.v5.stockTransfers.urls")),
    path("api/v5/journals/", include("api.v5.journals.urls")),
    path("api/v5/countries/", include("api.v5.countries.urls")),
    path("api/v5/states/", include("api.v5.states.urls")),
    path("api/v5/businessTypes/", include("api.v5.businessTypes.urls")),
    path("api/v5/organizations/", include("api.v5.organizations.urls")),
    path("api/v5/userTable/", include("api.v5.userTable.urls")),
    path("api/v5/translate/", include("api.v5.translate.urls")),
    path("api/v5/dashboard/", include("api.v5.dashboard.urls")),
    path("api/v5/userTypes/", include("api.v5.userTypes.urls")),
    path("api/v5/category/", include("api.v5.category.urls")),
    path("api/v5/workingTime/", include("api.v5.workingTime.urls")),
    path("api/v5/holiday/", include("api.v5.holiday.urls")),
    path("api/v5/salaryComponent/", include("api.v5.salaryComponent.urls")),
    path("api/v5/salaryKit/", include("api.v5.salaryKit.urls")),
    path("api/v5/salaryPeriod/", include("api.v5.salaryPeriod.urls")),
    path("api/v5/leave/", include("api.v5.leave.urls")),
    path("api/v5/leaveType/", include("api.v5.leaveType.urls")),
    path("api/v5/attendance/", include("api.v5.attendance.urls")),
    path("api/v5/advanceRequest/", include("api.v5.advanceRequest.urls")),
    path("api/v5/loanRequest/", include("api.v5.loanRequest.urls")),
    path("api/v5/loanType/", include("api.v5.loanType.urls")),
    path("api/v5/relieveRequest/", include("api.v5.relieveRequest.urls")),
    path("api/v5/leaveRequest/", include("api.v5.leaveRequest.urls")),
    path("api/v5/loyaltyCustomer/", include("api.v5.loyaltyCustomer.urls")),
    path("api/v5/loyaltyProgram/", include("api.v5.loyaltyProgram.urls")),
    path(
        "api/v5/bankReconciliationStatement/",
        include("api.v5.bankReconciliationStatement.urls"),
    ),
    path(
        "api/v5/reset-password/",
        include("django_rest_passwordreset.urls", namespace="password_reset5"),
    ),
    # version6 urls
    path("api/v6/users/", include("api.v6.users.urls")),
    path("api/v6/brands/", include("api.v6.brands.urls")),
    path("api/v6/units/", include("api.v6.units.urls")),
    path("api/v6/routes/", include("api.v6.routes.urls")),
    path("api/v6/taxCategories/", include("api.v6.taxCategories.urls")),
    path("api/v6/productCategories/", include("api.v6.productCategories.urls")),
    path("api/v6/productGroups/", include("api.v6.productGroups.urls")),
    path("api/v6/warehouses/", include("api.v6.warehouses.urls")),
    path("api/v6/priceCategories/", include("api.v6.priceCategories.urls")),
    path("api/v6/accountGroups/", include("api.v6.accountGroups.urls")),
    path("api/v6/accountLedgers/", include("api.v6.accountLedgers.urls")),
    path("api/v6/branchs/", include("api.v6.branchs.urls")),
    path("api/v6/parties/", include("api.v6.parties.urls")),
    path("api/v6/products/", include("api.v6.products.urls")),
    path("api/v6/priceLists/", include("api.v6.priceLists.urls")),
    path("api/v6/masterTypes/", include("api.v6.masterTypes.urls")),
    path("api/v6/transactionTypes/", include("api.v6.transactionTypes.urls")),
    path("api/v6/colors/", include("api.v6.colors.urls")),
    path("api/v6/companySettings/", include("api.v6.companySettings.urls")),
    path("api/v6/damageStockDetails/", include("api.v6.damageStockDetails.urls")),
    path("api/v6/damageStockMaster/", include("api.v6.damageStockMaster.urls")),
    path("api/v6/designation/", include("api.v6.designation.urls")),
    path("api/v6/department/", include("api.v6.department.urls")),
    path("api/v6/employees/", include("api.v6.employees.urls")),
    path("api/v6/flavours/", include("api.v6.flavours.urls")),
    path("api/v6/journalDetails/", include("api.v6.journalDetails.urls")),
    path("api/v6/journalMaster/", include("api.v6.journalMaster.urls")),
    path("api/v6/kitchen/", include("api.v6.kitchen.urls")),
    path("api/v6/ledgerPosting/", include("api.v6.ledgerPosting.urls")),
    path("api/v6/openingStockDetails/", include("api.v6.openingStockDetails.urls")),
    path("api/v6/openingStockMaster/", include("api.v6.openingStockMaster.urls")),
    path("api/v6/paymentDetails/", include("api.v6.paymentDetails.urls")),
    path("api/v6/paymentMaster/", include("api.v6.paymentMaster.urls")),
    path("api/v6/POSHoldDetails/", include("api.v6.POSHoldDetails.urls")),
    path("api/v6/POSHoldMaster/", include("api.v6.POSHoldMaster.urls")),
    path("api/v6/purchaseDetails/", include("api.v6.purchaseDetails.urls")),
    path("api/v6/purchaseMaster/", include("api.v6.purchaseMaster.urls")),
    path("api/v6/purchaseOrderDetails/", include("api.v6.purchaseOrderDetails.urls")),
    path("api/v6/purchaseOrderMaster/", include("api.v6.purchaseOrderMaster.urls")),
    path("api/v6/purchaseReturnDetails/", include("api.v6.purchaseReturnDetails.urls")),
    path("api/v6/purchaseReturnMaster/", include("api.v6.purchaseReturnMaster.urls")),
    path("api/v6/receiptDetails/", include("api.v6.receiptDetails.urls")),
    path("api/v6/receiptMaster/", include("api.v6.receiptMaster.urls")),
    path("api/v6/salesDetails/", include("api.v6.salesDetails.urls")),
    path("api/v6/salesMaster/", include("api.v6.salesMaster.urls")),
    path("api/v6/salesOrderDetails/", include("api.v6.salesOrderDetails.urls")),
    path("api/v6/salesOrderMaster/", include("api.v6.salesOrderMaster.urls")),
    path("api/v6/salesReturnDetails/", include("api.v6.salesReturnDetails.urls")),
    path("api/v6/salesReturnMaster/", include("api.v6.salesReturnMaster.urls")),
    path(
        "api/v6/settings/", include("api.v6.settings.urls", namespace="api_v6_settings")
    ),
    path(
        "api/v6/stockAdjustmentDetails/", include("api.v6.stockAdjustmentDetails.urls")
    ),
    path("api/v6/stockAdjustmentMaster/", include("api.v6.stockAdjustmentMaster.urls")),
    path("api/v6/stockReceiptDetails/", include("api.v6.stockReceiptDetails.urls")),
    path("api/v6/stockReceiptMasterID/", include("api.v6.stockReceiptMasterID.urls")),
    path("api/v6/stockTransferDetails/", include("api.v6.stockTransferDetails.urls")),
    path("api/v6/stockTransferMasterID/", include("api.v6.stockTransferMasterID.urls")),
    path("api/v6/stockPostings/", include("api.v6.stockPostings.urls")),
    path("api/v6/stockRates/", include("api.v6.stockRates.urls")),
    path("api/v6/banks/", include("api.v6.banks.urls")),
    path("api/v6/financialYear/", include("api.v6.financialYear.urls")),
    path("api/v6/workOrder/", include("api.v6.workOrder.urls")),
    path("api/v6/damageStock/", include("api.v6.damageStock.urls")),
    path("api/v6/openingStock/", include("api.v6.openingStock.urls")),
    path("api/v6/payments/", include("api.v6.payments.urls")),
    path("api/v6/posholds/", include("api.v6.posholds.urls")),
    path("api/v6/purchases/", include("api.v6.purchases.urls")),
    path("api/v6/receipts/", include("api.v6.receipts.urls")),
    path("api/v6/purchaseOrders/", include("api.v6.purchaseOrders.urls")),
    path("api/v6/purchaseReturns/", include("api.v6.purchaseReturns.urls")),
    path("api/v6/sales/", include("api.v6.sales.urls")),
    path("api/v6/salesOrders/", include("api.v6.salesOrders.urls")),
    path("api/v6/salesEstimates/", include("api.v6.salesEstimates.urls")),
    path("api/v6/salesReturns/", include("api.v6.salesReturns.urls")),
    path("api/v6/stockAdjustments/", include("api.v6.stockAdjustments.urls")),
    path("api/v6/stockReceipts/", include("api.v6.stockReceipts.urls")),
    path("api/v6/stockTransfers/", include("api.v6.stockTransfers.urls")),
    path("api/v6/journals/", include("api.v6.journals.urls")),
    path("api/v6/countries/", include("api.v6.countries.urls")),
    path("api/v6/states/", include("api.v6.states.urls")),
    path("api/v6/businessTypes/", include("api.v6.businessTypes.urls")),
    path("api/v6/organizations/", include("api.v6.organizations.urls")),
    path("api/v6/userTable/", include("api.v6.userTable.urls")),
    path("api/v6/translate/", include("api.v6.translate.urls")),
    path("api/v6/dashboard/", include("api.v6.dashboard.urls")),
    path("api/v6/userTypes/", include("api.v6.userTypes.urls")),
    path("api/v6/category/", include("api.v6.category.urls")),
    path("api/v6/workingTime/", include("api.v6.workingTime.urls")),
    path("api/v6/holiday/", include("api.v6.holiday.urls")),
    path("api/v6/salaryComponent/", include("api.v6.salaryComponent.urls")),
    path("api/v6/salaryKit/", include("api.v6.salaryKit.urls")),
    path("api/v6/salaryPeriod/", include("api.v6.salaryPeriod.urls")),
    path("api/v6/leave/", include("api.v6.leave.urls")),
    path("api/v6/leaveType/", include("api.v6.leaveType.urls")),
    path("api/v6/attendance/", include("api.v6.attendance.urls")),
    path("api/v6/advanceRequest/", include("api.v6.advanceRequest.urls")),
    path("api/v6/loanRequest/", include("api.v6.loanRequest.urls")),
    path("api/v6/loanType/", include("api.v6.loanType.urls")),
    path("api/v6/relieveRequest/", include("api.v6.relieveRequest.urls")),
    path("api/v6/leaveRequest/", include("api.v6.leaveRequest.urls")),
    path("api/v6/loyaltyCustomer/", include("api.v6.loyaltyCustomer.urls")),
    path("api/v6/loyaltyProgram/", include("api.v6.loyaltyProgram.urls")),
    path(
        "api/v6/bankReconciliationStatement/",
        include("api.v6.bankReconciliationStatement.urls"),
    ),
    path("api/v6/expense/", include("api.v6.expense.urls")),
    path(
        "api/v6/reset-password/",
        include("django_rest_passwordreset.urls", namespace="password_reset6"),
    ),
    # version 7 urls
    path("api/v7/users/", include("api.v7.users.urls")),
    path("api/v7/brands/", include("api.v7.brands.urls")),
    path("api/v7/units/", include("api.v7.units.urls")),
    path("api/v7/routes/", include("api.v7.routes.urls")),
    path("api/v7/taxCategories/", include("api.v7.taxCategories.urls")),
    path("api/v7/productCategories/", include("api.v7.productCategories.urls")),
    path("api/v7/productGroups/", include("api.v7.productGroups.urls")),
    path("api/v7/warehouses/", include("api.v7.warehouses.urls")),
    path("api/v7/priceCategories/", include("api.v7.priceCategories.urls")),
    path("api/v7/accountGroups/", include("api.v7.accountGroups.urls")),
    path("api/v7/accountLedgers/", include("api.v7.accountLedgers.urls")),
    path("api/v7/branchs/", include("api.v7.branchs.urls")),
    path("api/v7/parties/", include("api.v7.parties.urls")),
    path("api/v7/products/", include("api.v7.products.urls")),
    path("api/v7/priceLists/", include("api.v7.priceLists.urls")),
    path("api/v7/masterTypes/", include("api.v7.masterTypes.urls")),
    path("api/v7/transactionTypes/", include("api.v7.transactionTypes.urls")),
    path("api/v7/colors/", include("api.v7.colors.urls")),
    path("api/v7/companySettings/", include("api.v7.companySettings.urls")),
    path("api/v7/damageStockDetails/", include("api.v7.damageStockDetails.urls")),
    path("api/v7/damageStockMaster/", include("api.v7.damageStockMaster.urls")),
    path("api/v7/designation/", include("api.v7.designation.urls")),
    path("api/v7/department/", include("api.v7.department.urls")),
    path("api/v7/employees/", include("api.v7.employees.urls")),
    path("api/v7/flavours/", include("api.v7.flavours.urls")),
    path("api/v7/journalDetails/", include("api.v7.journalDetails.urls")),
    path("api/v7/journalMaster/", include("api.v7.journalMaster.urls")),
    path("api/v7/kitchen/", include("api.v7.kitchen.urls")),
    path("api/v7/ledgerPosting/", include("api.v7.ledgerPosting.urls")),
    path("api/v7/openingStockDetails/", include("api.v7.openingStockDetails.urls")),
    path("api/v7/openingStockMaster/", include("api.v7.openingStockMaster.urls")),
    path("api/v7/paymentDetails/", include("api.v7.paymentDetails.urls")),
    path("api/v7/paymentMaster/", include("api.v7.paymentMaster.urls")),
    path("api/v7/POSHoldDetails/", include("api.v7.POSHoldDetails.urls")),
    path("api/v7/POSHoldMaster/", include("api.v7.POSHoldMaster.urls")),
    path("api/v7/purchaseDetails/", include("api.v7.purchaseDetails.urls")),
    path("api/v7/purchaseMaster/", include("api.v7.purchaseMaster.urls")),
    path("api/v7/purchaseOrderDetails/", include("api.v7.purchaseOrderDetails.urls")),
    path("api/v7/purchaseOrderMaster/", include("api.v7.purchaseOrderMaster.urls")),
    path("api/v7/purchaseReturnDetails/", include("api.v7.purchaseReturnDetails.urls")),
    path("api/v7/purchaseReturnMaster/", include("api.v7.purchaseReturnMaster.urls")),
    path("api/v7/receiptDetails/", include("api.v7.receiptDetails.urls")),
    path("api/v7/receiptMaster/", include("api.v7.receiptMaster.urls")),
    path("api/v7/salesDetails/", include("api.v7.salesDetails.urls")),
    path("api/v7/salesMaster/", include("api.v7.salesMaster.urls")),
    path("api/v7/salesOrderDetails/", include("api.v7.salesOrderDetails.urls")),
    path("api/v7/salesOrderMaster/", include("api.v7.salesOrderMaster.urls")),
    path("api/v7/salesReturnDetails/", include("api.v7.salesReturnDetails.urls")),
    path("api/v7/salesReturnMaster/", include("api.v7.salesReturnMaster.urls")),
    path(
        "api/v7/settings/", include("api.v7.settings.urls", namespace="api_v7_settings")
    ),
    path(
        "api/v7/stockAdjustmentDetails/", include("api.v7.stockAdjustmentDetails.urls")
    ),
    path("api/v7/stockAdjustmentMaster/", include("api.v7.stockAdjustmentMaster.urls")),
    path("api/v7/stockReceiptDetails/", include("api.v7.stockReceiptDetails.urls")),
    path("api/v7/stockReceiptMasterID/", include("api.v7.stockReceiptMasterID.urls")),
    path("api/v7/stockTransferDetails/", include("api.v7.stockTransferDetails.urls")),
    path("api/v7/stockTransferMasterID/", include("api.v7.stockTransferMasterID.urls")),
    path("api/v7/stockPostings/", include("api.v7.stockPostings.urls")),
    path("api/v7/stockRates/", include("api.v7.stockRates.urls")),
    path("api/v7/banks/", include("api.v7.banks.urls")),
    path("api/v7/financialYear/", include("api.v7.financialYear.urls")),
    path("api/v7/workOrder/", include("api.v7.workOrder.urls")),
    path("api/v7/damageStock/", include("api.v7.damageStock.urls")),
    path("api/v7/openingStock/", include("api.v7.openingStock.urls")),
    path("api/v7/payments/", include("api.v7.payments.urls")),
    path("api/v7/posholds/", include("api.v7.posholds.urls")),
    path("api/v7/purchases/", include("api.v7.purchases.urls")),
    path("api/v7/receipts/", include("api.v7.receipts.urls")),
    path("api/v7/purchaseOrders/", include("api.v7.purchaseOrders.urls")),
    path("api/v7/purchaseReturns/", include("api.v7.purchaseReturns.urls")),
    path("api/v7/sales/", include("api.v7.sales.urls")),
    path("api/v7/salesOrders/", include("api.v7.salesOrders.urls")),
    path("api/v7/salesEstimates/", include("api.v7.salesEstimates.urls")),
    path("api/v7/salesReturns/", include("api.v7.salesReturns.urls")),
    path("api/v7/stockAdjustments/", include("api.v7.stockAdjustments.urls")),
    path("api/v7/stockReceipts/", include("api.v7.stockReceipts.urls")),
    path("api/v7/stockTransfers/", include("api.v7.stockTransfers.urls")),
    path("api/v7/journals/", include("api.v7.journals.urls")),
    path("api/v7/countries/", include("api.v7.countries.urls")),
    path("api/v7/states/", include("api.v7.states.urls")),
    path("api/v7/businessTypes/", include("api.v7.businessTypes.urls")),
    path("api/v7/organizations/", include("api.v7.organizations.urls")),
    path("api/v7/userTable/", include("api.v7.userTable.urls")),
    path("api/v7/translate/", include("api.v7.translate.urls")),
    path("api/v7/dashboard/", include("api.v7.dashboard.urls")),
    path("api/v7/userTypes/", include("api.v7.userTypes.urls")),
    path("api/v7/category/", include("api.v7.category.urls")),
    path("api/v7/workingTime/", include("api.v7.workingTime.urls")),
    path("api/v7/holiday/", include("api.v7.holiday.urls")),
    path("api/v7/salaryComponent/", include("api.v7.salaryComponent.urls")),
    path("api/v7/salaryKit/", include("api.v7.salaryKit.urls")),
    path("api/v7/salaryPeriod/", include("api.v7.salaryPeriod.urls")),
    path("api/v7/leave/", include("api.v7.leave.urls")),
    path("api/v7/leaveType/", include("api.v7.leaveType.urls")),
    path("api/v7/attendance/", include("api.v7.attendance.urls")),
    path("api/v7/advanceRequest/", include("api.v7.advanceRequest.urls")),
    path("api/v7/loanRequest/", include("api.v7.loanRequest.urls")),
    path("api/v7/loanType/", include("api.v7.loanType.urls")),
    path("api/v7/relieveRequest/", include("api.v7.relieveRequest.urls")),
    path("api/v7/leaveRequest/", include("api.v7.leaveRequest.urls")),
    path("api/v7/loyaltyCustomer/", include("api.v7.loyaltyCustomer.urls")),
    path("api/v7/loyaltyProgram/", include("api.v7.loyaltyProgram.urls")),
    path(
        "api/v7/bankReconciliationStatement/",
        include("api.v7.bankReconciliationStatement.urls"),
    ),
    path("api/v7/expense/", include("api.v7.expense.urls")),
    path(
        "api/v7/reset-password/",
        include("django_rest_passwordreset.urls", namespace="password_reset7"),
    ),
    # version 8 urls
    path("api/v8/users/", include("api.v8.users.urls")),
    path("api/v8/brands/", include("api.v8.brands.urls")),
    path("api/v8/units/", include("api.v8.units.urls")),
    path("api/v8/routes/", include("api.v8.routes.urls")),
    path("api/v8/taxCategories/", include("api.v8.taxCategories.urls")),
    path("api/v8/productCategories/", include("api.v8.productCategories.urls")),
    path("api/v8/productGroups/", include("api.v8.productGroups.urls")),
    path("api/v8/warehouses/", include("api.v8.warehouses.urls")),
    path("api/v8/priceCategories/", include("api.v8.priceCategories.urls")),
    path("api/v8/accountGroups/", include("api.v8.accountGroups.urls")),
    path("api/v8/accountLedgers/", include("api.v8.accountLedgers.urls")),
    path("api/v8/branchs/", include("api.v8.branchs.urls")),
    path("api/v8/parties/", include("api.v8.parties.urls")),
    path("api/v8/products/", include("api.v8.products.urls")),
    path("api/v8/priceLists/", include("api.v8.priceLists.urls")),
    path("api/v8/masterTypes/", include("api.v8.masterTypes.urls")),
    path("api/v8/transactionTypes/", include("api.v8.transactionTypes.urls")),
    path("api/v8/colors/", include("api.v8.colors.urls")),
    path("api/v8/companySettings/", include("api.v8.companySettings.urls")),
    path("api/v8/damageStockDetails/", include("api.v8.damageStockDetails.urls")),
    path("api/v8/damageStockMaster/", include("api.v8.damageStockMaster.urls")),
    path("api/v8/designation/", include("api.v8.designation.urls")),
    path("api/v8/department/", include("api.v8.department.urls")),
    path("api/v8/employees/", include("api.v8.employees.urls")),
    path("api/v8/flavours/", include("api.v8.flavours.urls")),
    path("api/v8/journalDetails/", include("api.v8.journalDetails.urls")),
    path("api/v8/journalMaster/", include("api.v8.journalMaster.urls")),
    path("api/v8/kitchen/", include("api.v8.kitchen.urls")),
    path("api/v8/ledgerPosting/", include("api.v8.ledgerPosting.urls")),
    path("api/v8/openingStockDetails/", include("api.v8.openingStockDetails.urls")),
    path("api/v8/openingStockMaster/", include("api.v8.openingStockMaster.urls")),
    path("api/v8/paymentDetails/", include("api.v8.paymentDetails.urls")),
    path("api/v8/paymentMaster/", include("api.v8.paymentMaster.urls")),
    path("api/v8/POSHoldDetails/", include("api.v8.POSHoldDetails.urls")),
    path("api/v8/POSHoldMaster/", include("api.v8.POSHoldMaster.urls")),
    path("api/v8/purchaseDetails/", include("api.v8.purchaseDetails.urls")),
    path("api/v8/purchaseMaster/", include("api.v8.purchaseMaster.urls")),
    path("api/v8/purchaseOrderDetails/", include("api.v8.purchaseOrderDetails.urls")),
    path("api/v8/purchaseOrderMaster/", include("api.v8.purchaseOrderMaster.urls")),
    path("api/v8/purchaseReturnDetails/", include("api.v8.purchaseReturnDetails.urls")),
    path("api/v8/purchaseReturnMaster/", include("api.v8.purchaseReturnMaster.urls")),
    path("api/v8/receiptDetails/", include("api.v8.receiptDetails.urls")),
    path("api/v8/receiptMaster/", include("api.v8.receiptMaster.urls")),
    path("api/v8/salesDetails/", include("api.v8.salesDetails.urls")),
    path("api/v8/salesMaster/", include("api.v8.salesMaster.urls")),
    path("api/v8/salesOrderDetails/", include("api.v8.salesOrderDetails.urls")),
    path("api/v8/salesOrderMaster/", include("api.v8.salesOrderMaster.urls")),
    path("api/v8/salesReturnDetails/", include("api.v8.salesReturnDetails.urls")),
    path("api/v8/salesReturnMaster/", include("api.v8.salesReturnMaster.urls")),
    path(
        "api/v8/settings/", include("api.v8.settings.urls", namespace="api_v8_settings")
    ),
    path(
        "api/v8/stockAdjustmentDetails/", include("api.v8.stockAdjustmentDetails.urls")
    ),
    path("api/v8/stockAdjustmentMaster/", include("api.v8.stockAdjustmentMaster.urls")),
    path("api/v8/stockReceiptDetails/", include("api.v8.stockReceiptDetails.urls")),
    path("api/v8/stockReceiptMasterID/", include("api.v8.stockReceiptMasterID.urls")),
    path("api/v8/stockTransferDetails/", include("api.v8.stockTransferDetails.urls")),
    path("api/v8/stockTransferMasterID/", include("api.v8.stockTransferMasterID.urls")),
    path("api/v8/stockPostings/", include("api.v8.stockPostings.urls")),
    path("api/v8/stockRates/", include("api.v8.stockRates.urls")),
    path("api/v8/banks/", include("api.v8.banks.urls")),
    path("api/v8/financialYear/", include("api.v8.financialYear.urls")),
    path("api/v8/workOrder/", include("api.v8.workOrder.urls")),
    path("api/v8/damageStock/", include("api.v8.damageStock.urls")),
    path("api/v8/openingStock/", include("api.v8.openingStock.urls")),
    path("api/v8/payments/", include("api.v8.payments.urls")),
    path("api/v8/posholds/", include("api.v8.posholds.urls")),
    path("api/v8/purchases/", include("api.v8.purchases.urls")),
    path("api/v8/receipts/", include("api.v8.receipts.urls")),
    path("api/v8/purchaseOrders/", include("api.v8.purchaseOrders.urls")),
    path("api/v8/purchaseReturns/", include("api.v8.purchaseReturns.urls")),
    path("api/v8/sales/", include("api.v8.sales.urls")),
    path("api/v8/salesOrders/", include("api.v8.salesOrders.urls")),
    path("api/v8/salesEstimates/", include("api.v8.salesEstimates.urls")),
    path("api/v8/salesReturns/", include("api.v8.salesReturns.urls")),
    path("api/v8/stockAdjustments/", include("api.v8.stockAdjustments.urls")),
    path("api/v8/stockReceipts/", include("api.v8.stockReceipts.urls")),
    path("api/v8/stockTransfers/", include("api.v8.stockTransfers.urls")),
    path("api/v8/journals/", include("api.v8.journals.urls")),
    path("api/v8/countries/", include("api.v8.countries.urls")),
    path("api/v8/states/", include("api.v8.states.urls")),
    path("api/v8/businessTypes/", include("api.v8.businessTypes.urls")),
    path("api/v8/organizations/", include("api.v8.organizations.urls")),
    path("api/v8/userTable/", include("api.v8.userTable.urls")),
    path("api/v8/translate/", include("api.v8.translate.urls")),
    path("api/v8/dashboard/", include("api.v8.dashboard.urls")),
    path("api/v8/userTypes/", include("api.v8.userTypes.urls")),
    path("api/v8/category/", include("api.v8.category.urls")),
    path("api/v8/workingTime/", include("api.v8.workingTime.urls")),
    path("api/v8/holiday/", include("api.v8.holiday.urls")),
    path("api/v8/salaryComponent/", include("api.v8.salaryComponent.urls")),
    path("api/v8/salaryKit/", include("api.v8.salaryKit.urls")),
    path("api/v8/salaryPeriod/", include("api.v8.salaryPeriod.urls")),
    path("api/v8/leave/", include("api.v8.leave.urls")),
    path("api/v8/leaveType/", include("api.v8.leaveType.urls")),
    path("api/v8/attendance/", include("api.v8.attendance.urls")),
    path("api/v8/advanceRequest/", include("api.v8.advanceRequest.urls")),
    path("api/v8/loanRequest/", include("api.v8.loanRequest.urls")),
    path("api/v8/loanType/", include("api.v8.loanType.urls")),
    path("api/v8/relieveRequest/", include("api.v8.relieveRequest.urls")),
    path("api/v8/leaveRequest/", include("api.v8.leaveRequest.urls")),
    path("api/v8/loyaltyCustomer/", include("api.v8.loyaltyCustomer.urls")),
    path("api/v8/loyaltyProgram/", include("api.v8.loyaltyProgram.urls")),
    path(
        "api/v8/bankReconciliationStatement/",
        include("api.v8.bankReconciliationStatement.urls"),
    ),
    path("api/v8/expense/", include("api.v8.expense.urls")),
    path("api/v8/pos_apis/", include("api.v8.pos_apis.urls")),
    path("api/v8/salesApp/", include("api.v8.salesApp.urls")),
    path(
        "api/v8/reset-password/",

        include("django_rest_passwordreset.urls", namespace="password_reset8"),
    ),
    # version 9 urls
    path("api/v9/users/", include("api.v9.users.urls")),
    path("api/v9/brands/", include("api.v9.brands.urls",namespace="brands9")),

    # version 9 urls
    path("api/v9/units/", include("api.v9.units.urls")),
    path("api/v9/routes/", include("api.v9.routes.urls")),
    path("api/v9/taxCategories/", include("api.v9.taxCategories.urls")),
    path("api/v9/productCategories/", include("api.v9.productCategories.urls")),
    path("api/v9/productGroups/", include("api.v9.productGroups.urls")),
    path("api/v9/warehouses/", include("api.v9.warehouses.urls")),
    path("api/v9/priceCategories/", include("api.v9.priceCategories.urls")),
    path("api/v9/accountGroups/", include("api.v9.accountGroups.urls")),
    path("api/v9/accountLedgers/", include("api.v9.accountLedgers.urls")),
    path("api/v9/branchs/", include("api.v9.branchs.urls")),
    path("api/v9/parties/", include("api.v9.parties.urls")),
    path("api/v9/products/", include("api.v9.products.urls")),
    path("api/v9/priceLists/", include("api.v9.priceLists.urls")),
    path("api/v9/masterTypes/", include("api.v9.masterTypes.urls")),
    path("api/v9/transactionTypes/", include("api.v9.transactionTypes.urls")),
    path("api/v9/colors/", include("api.v9.colors.urls")),
    path("api/v9/companySettings/", include("api.v9.companySettings.urls")),
    path("api/v9/damageStockDetails/", include("api.v9.damageStockDetails.urls")),
    path("api/v9/damageStockMaster/", include("api.v9.damageStockMaster.urls")),
    path("api/v9/designation/", include("api.v9.designation.urls")),
    path("api/v9/department/", include("api.v9.department.urls")),
    path("api/v9/employees/", include("api.v9.employees.urls")),
    path("api/v9/flavours/", include("api.v9.flavours.urls")),
    path("api/v9/journalDetails/", include("api.v9.journalDetails.urls")),
    path("api/v9/journalMaster/", include("api.v9.journalMaster.urls")),
    path("api/v9/kitchen/", include("api.v9.kitchen.urls")),
    path("api/v9/ledgerPosting/", include("api.v9.ledgerPosting.urls")),
    path("api/v9/openingStockDetails/", include("api.v9.openingStockDetails.urls")),
    path("api/v9/openingStockMaster/", include("api.v9.openingStockMaster.urls")),
    path("api/v9/paymentDetails/", include("api.v9.paymentDetails.urls")),
    path("api/v9/paymentMaster/", include("api.v9.paymentMaster.urls")),
    path("api/v9/POSHoldDetails/", include("api.v9.POSHoldDetails.urls")),
    path("api/v9/POSHoldMaster/", include("api.v9.POSHoldMaster.urls")),
    path("api/v9/purchaseDetails/", include("api.v9.purchaseDetails.urls")),
    path("api/v9/purchaseMaster/", include("api.v9.purchaseMaster.urls")),
    path("api/v9/purchaseOrderDetails/", include("api.v9.purchaseOrderDetails.urls")),
    path("api/v9/purchaseOrderMaster/", include("api.v9.purchaseOrderMaster.urls")),
    path("api/v9/purchaseReturnDetails/", include("api.v9.purchaseReturnDetails.urls")),
    path("api/v9/purchaseReturnMaster/", include("api.v9.purchaseReturnMaster.urls")),
    path("api/v9/receiptDetails/", include("api.v9.receiptDetails.urls")),
    path("api/v9/receiptMaster/", include("api.v9.receiptMaster.urls")),
    path("api/v9/salesDetails/", include("api.v9.salesDetails.urls")),
    path("api/v9/salesMaster/", include("api.v9.salesMaster.urls")),
    path("api/v9/salesOrderDetails/", include("api.v9.salesOrderDetails.urls")),
    path("api/v9/salesOrderMaster/", include("api.v9.salesOrderMaster.urls")),
    path("api/v9/salesReturnDetails/", include("api.v9.salesReturnDetails.urls")),
    path("api/v9/salesReturnMaster/", include("api.v9.salesReturnMaster.urls")),
    path(
        "api/v9/settings/", include("api.v9.settings.urls", namespace="api_v9_settings")
    ),
    path(
        "api/v9/stockAdjustmentDetails/", include("api.v9.stockAdjustmentDetails.urls")
    ),
    path("api/v9/stockAdjustmentMaster/", include("api.v9.stockAdjustmentMaster.urls")),
    path("api/v9/stockReceiptDetails/", include("api.v9.stockReceiptDetails.urls")),
    path("api/v9/stockReceiptMasterID/", include("api.v9.stockReceiptMasterID.urls")),
    path("api/v9/stockTransferDetails/", include("api.v9.stockTransferDetails.urls")),
    path("api/v9/stockTransferMasterID/", include("api.v9.stockTransferMasterID.urls")),
    path("api/v9/stockPostings/", include("api.v9.stockPostings.urls")),
    path("api/v9/stockRates/", include("api.v9.stockRates.urls")),
    path("api/v9/banks/", include("api.v9.banks.urls")),
    path("api/v9/financialYear/", include("api.v9.financialYear.urls")),
    path("api/v9/workOrder/", include("api.v9.workOrder.urls")),
    path("api/v9/damageStock/", include("api.v9.damageStock.urls")),
    path("api/v9/openingStock/", include("api.v9.openingStock.urls")),
    path("api/v9/payments/", include("api.v9.payments.urls")),
    path("api/v9/posholds/", include("api.v9.posholds.urls")),
    path("api/v9/purchases/", include("api.v9.purchases.urls")),
    path("api/v9/receipts/", include("api.v9.receipts.urls")),
    path("api/v9/purchaseOrders/", include("api.v9.purchaseOrders.urls")),
    path("api/v9/purchaseReturns/", include("api.v9.purchaseReturns.urls")),
    path("api/v9/sales/", include("api.v9.sales.urls")),
    path("api/v9/salesOrders/", include("api.v9.salesOrders.urls")),
    path("api/v9/salesEstimates/", include("api.v9.salesEstimates.urls")),
    path("api/v9/salesReturns/", include("api.v9.salesReturns.urls")),
    path("api/v9/stockAdjustments/", include("api.v9.stockAdjustments.urls")),
    path("api/v9/stockManagements/", include("api.v9.stockManagements.urls")),
    path("api/v9/stockReceipts/", include("api.v9.stockReceipts.urls")),
    path("api/v9/stockTransfers/", include("api.v9.stockTransfers.urls")),
    path("api/v9/journals/", include("api.v9.journals.urls")),
    path("api/v9/countries/", include("api.v9.countries.urls")),
    path("api/v9/states/", include("api.v9.states.urls")),
    path("api/v9/businessTypes/", include("api.v9.businessTypes.urls")),
    path("api/v9/organizations/", include("api.v9.organizations.urls")),
    path("api/v9/userTable/", include("api.v9.userTable.urls")),
    path("api/v9/translate/", include("api.v9.translate.urls")),
    path("api/v9/dashboard/", include("api.v9.dashboard.urls")),
    path("api/v9/userTypes/", include("api.v9.userTypes.urls")),
    path("api/v9/category/", include("api.v9.category.urls")),
    path("api/v9/workingTime/", include("api.v9.workingTime.urls")),
    path("api/v9/holiday/", include("api.v9.holiday.urls")),
    path("api/v9/salaryComponent/", include("api.v9.salaryComponent.urls")),
    path("api/v9/salaryKit/", include("api.v9.salaryKit.urls")),
    path("api/v9/salaryPeriod/", include("api.v9.salaryPeriod.urls")),
    path("api/v9/leave/", include("api.v9.leave.urls")),
    path("api/v9/leaveType/", include("api.v9.leaveType.urls")),
    path("api/v9/attendance/", include("api.v9.attendance.urls")),
    path("api/v9/advanceRequest/", include("api.v9.advanceRequest.urls")),
    path("api/v9/loanRequest/", include("api.v9.loanRequest.urls")),
    path("api/v9/loanType/", include("api.v9.loanType.urls")),
    path("api/v9/relieveRequest/", include("api.v9.relieveRequest.urls")),
    path("api/v9/leaveRequest/", include("api.v9.leaveRequest.urls")),
    path("api/v9/loyaltyCustomer/", include("api.v9.loyaltyCustomer.urls")),
    path("api/v9/loyaltyProgram/", include("api.v9.loyaltyProgram.urls")),
    path(
        "api/v9/bankReconciliationStatement/",
        include("api.v9.bankReconciliationStatement.urls",namespace="bankReconciliationStatement9"),

    ),
    path("api/v9/expense/", include("api.v9.expense.urls")),
    path("api/v9/pos_apis/", include("api.v9.pos_apis.urls")),
    path("api/v9/salesApp/", include("api.v9.salesApp.urls")),
    path(
        "api/v9/reset-password/",
        include("django_rest_passwordreset.urls", namespace="password_reset9"),
    ),
    path("api/v9/web/", include("api.v9.web.urls")),
    path("api/v9/reportQuerys/", include("api.v9.reportQuerys.urls")),
    path("api/v9/stockOrder/", include("api.v9.stockOrder.urls")),


    # version 10 urls
    path("api/v10/users/", include("api.v10.users.urls")),
    path("api/v10/brands/", include("api.v10.brands.urls")),
    path("api/v10/units/", include("api.v10.units.urls")),
    path("api/v10/routes/", include("api.v10.routes.urls")),
    path("api/v10/taxCategories/", include("api.v10.taxCategories.urls")),
    path("api/v10/productCategories/", include("api.v10.productCategories.urls")),
    path("api/v10/productGroups/", include("api.v10.productGroups.urls")),
    path("api/v10/warehouses/", include("api.v10.warehouses.urls")),
    path("api/v10/priceCategories/", include("api.v10.priceCategories.urls")),
    path("api/v10/accountGroups/", include("api.v10.accountGroups.urls")),
    path("api/v10/accountLedgers/", include("api.v10.accountLedgers.urls")),
    path("api/v10/branchs/", include("api.v10.branchs.urls")),
    path("api/v10/parties/", include("api.v10.parties.urls")),
    path("api/v10/products/", include("api.v10.products.urls")),
    path("api/v10/priceLists/", include("api.v10.priceLists.urls")),
    path("api/v10/masterTypes/", include("api.v10.masterTypes.urls")),
    path("api/v10/transactionTypes/", include("api.v10.transactionTypes.urls")),
    path("api/v10/colors/", include("api.v10.colors.urls")),
    path("api/v10/companySettings/", include("api.v10.companySettings.urls")),
    path("api/v10/damageStockDetails/", include("api.v10.damageStockDetails.urls")),
    path("api/v10/damageStockMaster/", include("api.v10.damageStockMaster.urls")),
    path("api/v10/designation/", include("api.v10.designation.urls")),
    path("api/v10/department/", include("api.v10.department.urls")),
    path("api/v10/employees/", include("api.v10.employees.urls")),
    path("api/v10/flavours/", include("api.v10.flavours.urls")),
    path("api/v10/journalDetails/", include("api.v10.journalDetails.urls")),
    path("api/v10/journalMaster/", include("api.v10.journalMaster.urls")),
    path("api/v10/kitchen/", include("api.v10.kitchen.urls")),
    path("api/v10/ledgerPosting/", include("api.v10.ledgerPosting.urls")),
    path("api/v10/openingStockDetails/", include("api.v10.openingStockDetails.urls")),
    path("api/v10/openingStockMaster/", include("api.v10.openingStockMaster.urls")),
    path("api/v10/paymentDetails/", include("api.v10.paymentDetails.urls")),
    path("api/v10/paymentMaster/", include("api.v10.paymentMaster.urls")),
    path("api/v10/POSHoldDetails/", include("api.v10.POSHoldDetails.urls")),
    path("api/v10/POSHoldMaster/", include("api.v10.POSHoldMaster.urls")),
    path("api/v10/purchaseDetails/", include("api.v10.purchaseDetails.urls")),
    path("api/v10/purchaseMaster/", include("api.v10.purchaseMaster.urls")),
    path("api/v10/purchaseOrderDetails/", include("api.v10.purchaseOrderDetails.urls")),
    path("api/v10/purchaseOrderMaster/", include("api.v10.purchaseOrderMaster.urls")),
    path("api/v10/purchaseReturnDetails/", include("api.v10.purchaseReturnDetails.urls")),
    path("api/v10/purchaseReturnMaster/", include("api.v10.purchaseReturnMaster.urls")),
    path("api/v10/receiptDetails/", include("api.v10.receiptDetails.urls")),
    path("api/v10/receiptMaster/", include("api.v10.receiptMaster.urls")),
    path("api/v10/salesDetails/", include("api.v10.salesDetails.urls")),
    path("api/v10/salesMaster/", include("api.v10.salesMaster.urls")),
    path("api/v10/salesOrderDetails/", include("api.v10.salesOrderDetails.urls")),
    path("api/v10/salesOrderMaster/", include("api.v10.salesOrderMaster.urls")),
    path("api/v10/salesReturnDetails/", include("api.v10.salesReturnDetails.urls")),
    path("api/v10/salesReturnMaster/", include("api.v10.salesReturnMaster.urls")),
    path(
        "api/v10/settings/", include("api.v10.settings.urls", namespace="api_v10_settings")
    ),
    path(
        "api/v10/stockAdjustmentDetails/", include("api.v10.stockAdjustmentDetails.urls")
    ),
    path("api/v10/stockAdjustmentMaster/", include("api.v10.stockAdjustmentMaster.urls")),
    path("api/v10/stockReceiptDetails/", include("api.v10.stockReceiptDetails.urls")),
    path("api/v10/stockReceiptMasterID/", include("api.v10.stockReceiptMasterID.urls")),
    path("api/v10/stockTransferDetails/", include("api.v10.stockTransferDetails.urls")),
    path("api/v10/stockTransferMasterID/", include("api.v10.stockTransferMasterID.urls")),
    path("api/v10/stockPostings/", include("api.v10.stockPostings.urls")),
    path("api/v10/stockRates/", include("api.v10.stockRates.urls")),
    path("api/v10/banks/", include("api.v10.banks.urls")),
    path("api/v10/financialYear/", include("api.v10.financialYear.urls")),
    path("api/v10/workOrder/", include("api.v10.workOrder.urls")),
    path("api/v10/damageStock/", include("api.v10.damageStock.urls")),
    path("api/v10/openingStock/", include("api.v10.openingStock.urls")),
    path("api/v10/payments/", include("api.v10.payments.urls")),
    path("api/v10/posholds/", include("api.v10.posholds.urls")),
    path("api/v10/purchases/", include("api.v10.purchases.urls")),
    path("api/v10/receipts/", include("api.v10.receipts.urls")),
    path("api/v10/purchaseOrders/", include("api.v10.purchaseOrders.urls")),
    path("api/v10/purchaseReturns/", include("api.v10.purchaseReturns.urls")),
    path("api/v10/sales/", include("api.v10.sales.urls")),
    path("api/v10/salesOrders/", include("api.v10.salesOrders.urls")),
    path("api/v10/salesEstimates/", include("api.v10.salesEstimates.urls")),
    path("api/v10/salesReturns/", include("api.v10.salesReturns.urls")),
    path("api/v10/stockAdjustments/", include("api.v10.stockAdjustments.urls")),
    path("api/v10/stockManagements/", include("api.v10.stockManagements.urls")),
    path("api/v10/stockReceipts/", include("api.v10.stockReceipts.urls")),
    path("api/v10/stockTransfers/", include("api.v10.stockTransfers.urls")),
    path("api/v10/journals/", include("api.v10.journals.urls")),
    path("api/v10/countries/", include("api.v10.countries.urls")),
    path("api/v10/states/", include("api.v10.states.urls")),
    path("api/v10/businessTypes/", include("api.v10.businessTypes.urls")),
    path("api/v10/organizations/", include("api.v10.organizations.urls")),
    path("api/v10/userTable/", include("api.v10.userTable.urls")),
    path("api/v10/translate/", include("api.v10.translate.urls")),
    path("api/v10/dashboard/", include("api.v10.dashboard.urls")),
    path("api/v10/userTypes/", include("api.v10.userTypes.urls")),
    path("api/v10/category/", include("api.v10.category.urls")),
    path("api/v10/workingTime/", include("api.v10.workingTime.urls")),
    path("api/v10/holiday/", include("api.v10.holiday.urls")),
    path("api/v10/salaryComponent/", include("api.v10.salaryComponent.urls")),
    path("api/v10/salaryKit/", include("api.v10.salaryKit.urls")),
    path("api/v10/salaryPeriod/", include("api.v10.salaryPeriod.urls")),
    path("api/v10/leave/", include("api.v10.leave.urls")),
    path("api/v10/leaveType/", include("api.v10.leaveType.urls")),
    path("api/v10/attendance/", include("api.v10.attendance.urls")),
    path("api/v10/advanceRequest/", include("api.v10.advanceRequest.urls")),
    path("api/v10/loanRequest/", include("api.v10.loanRequest.urls")),
    path("api/v10/loanType/", include("api.v10.loanType.urls")),
    path("api/v10/relieveRequest/", include("api.v10.relieveRequest.urls")),
    path("api/v10/leaveRequest/", include("api.v10.leaveRequest.urls")),
    path("api/v10/loyaltyCustomer/", include("api.v10.loyaltyCustomer.urls")),
    path("api/v10/loyaltyProgram/", include("api.v10.loyaltyProgram.urls")),
    path(
        "api/v10/bankReconciliationStatement/",
        include("api.v10.bankReconciliationStatement.urls"),
    ),
    path("api/v10/expense/", include("api.v10.expense.urls")),
    path("api/v10/pos_apis/", include("api.v10.pos_apis.urls")),
    path("api/v10/salesApp/", include("api.v10.salesApp.urls")),
    path(
        "api/v10/reset-password/",
        include("django_rest_passwordreset.urls", namespace="password_reset10"),
    ),
    path("api/v10/web/", include("api.v10.web.urls")),
    path("api/v10/reportQuerys/", include("api.v10.reportQuerys.urls")),
    path("api/v10/stockOrder/", include("api.v10.stockOrder.urls")),

    # path('api/v2/reset-password/', include('django_rest_passwordreset.urls', namespace='password_reset')),
    # path('api/v1/reset-password/', include('django_rest_passwordreset.urls', namespace='reset_password_confirm')),
    # path('api/v1/reset-password/verify-token/', users_views.CustomPasswordTokenVerificationView.as_view(), name='password_reset_verify_token'),
    # url(r'^',include(('web.urls', 'web'),namespace="web")),
    re_path(r"^celery-progress/", include("celery_progress.urls")),
    url(r"^", include("web.urls", namespace="web")),
    # url(r'^', include('users.urls', namespace="brands")),
    url(r"^users/", include(("users.urls", "users"), namespace="users")),
    url(r"^brands/", include(("brands.urls", "brands"), namespace="hello")),
    url(r"^main/", include(("main.urls", "main"), namespace="main")),
    url(r"^accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),
    url(
        r"^inventories/",
        include(("inventories.urls", "inventories"), namespace="inventories"),
    ),
    url(r"^payrolls/", include(("payrolls.urls", "payrolls"), namespace="payrolls")),
    url(
        r"^administrations/",
        include(
            ("administrations.urls", "administrations"), namespace="administrations"
        ),
    ),
    # url(r'^create-company/$',general_views.create_company,name='create_company'),
    # url(r'^(?# companies)/$',general_views.companies,name='companies'),
    url(r"^dashboard/$", general_views.dashboard, name="dashboard"),
    url(r"^index/$", general_views.index, name="index"),
    url(r"^form/$", general_views.form_view, name="form_view"),
    url(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    url(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_FILE_ROOT}),
]
